[[main]]
  name = "¿Quienes somos?"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Nuestra identidad"
  pageRef = "identity"
  weight = 20

[[main]]
  name = "Contactanos"
  pageRef = "contact"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"



[[footer]]
  name = "Privacidad"
  pageRef = "privacy"
  weight = 90

[[footer]]
  name = "SEO"
  url = "https://pagespeed.web.dev/analysis/https-montenegrodanielfelipe-com-softcial/9alzt6mbia?form_factor=desktop"
  weight = 100