[[main]]
  name = "¿Quienes somos?"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Contactanos"
  pageRef = "contact"
  weight = 20

[[main]]
  name = "Ingresar"
  url = "https://softcial-dynamic.vercel.app/sign-up"
  weight = 30


[[footer]]
  name = "Términos y Condiciones"
  pageRef = "terms-and-conditions"
  weight = 80

[[footer]]
  name = "Privacidad"
  pageRef = "privacy"
  weight = 90

[[footer]]
  name = "SEO"
  url = "https://pagespeed.web.dev/analysis/https-montenegrodanielfelipe-com-softcial/0rby0rq5hp?form_factor=desktop"
  weight = 100